# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 00:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scpc_location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUserLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=13, max_digits=15, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=13, max_digits=15, verbose_name='longitude')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Last Know Location',
                'verbose_name_plural': 'Last Know Locations',
            },
        ),
        migrations.RemoveField(
            model_name='lastknowlocation',
            name='user',
        ),
        migrations.DeleteModel(
            name='LastKnowLocation',
        ),
    ]
