# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 06:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scpc_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='ip address')),
                ('url', models.CharField(blank=True, max_length=255, null=True, verbose_name='url')),
                ('method', models.CharField(blank=True, max_length=255, null=True, verbose_name='method')),
                ('request_headers', models.TextField(blank=True, null=True, verbose_name='request headers')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='request body')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='response status')),
                ('validation_errors', models.TextField(blank=True, null=True, verbose_name='validation erros')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finished at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
            },
        ),
    ]
