# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 21:39
from __future__ import unicode_literals

from django.db import migrations
import scpc_core.models.managers


class Migration(migrations.Migration):

    dependencies = [
        ('scpc_core', '0002_request'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', scpc_core.models.managers.UserManager()),
            ],
        ),
    ]
